name: CreateRelease
on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]
    
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM and Meteor
        run: |
          curl https://install.meteor.com/ | sh
          npm install --production
      - name: Build bundle
        run: meteor build --server localhost:8265 --directory ../tdarr-linux-x64 --architecture os.linux.x86_64
      - uses: actions/upload-artifact@v1
        with:
          name: tdarr-linux-x64
          path: ../tdarr-linux-x64

  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [8.x]
    
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM and Meteor
        run: |
          curl https://install.meteor.com/ | sh
          npm install --production
      - name: Build bundle
        run: meteor build --server localhost:8265 --directory ../tdarr-osx-x64 --architecture os.osx.x86_64
      - uses: actions/upload-artifact@v1
        with:
          name: tdarr-osx-x64
          path: ../tdarr-osx-x64